dist: xenial
language: python
python:
- '3.6'
before_install:
- sudo apt-get update
- sudo apt-get install -y xvfb gimp python python-pip
- sudo pip2 install numpy typing
install:
- pip install pytest setuptools
- pip install -r requirements.txt
- pip install -e .
- python -m pgimp.doc.GimpDocumentationGenerator
script:
- pytest -c pytest.ini --maxfail=2 pgimp
deploy:
  provider: pypi
  user: mabu
  distributions: sdist
  password:
    secure: XiwvNFEp/l9sbot7faIr/SkSLR95kyM7VIPjueaDrJzpn9Q2jkzdrIaM+2HThSJ/VvDpcOtd3MYfM023jLISwXZMhz4Puj2u6IPLAclrICXY31FMtbqZsdN7Wjh9555ptnEdCZLppB2IfdtuKfkp7woO4LpNZbvpJUx1NRsHcO9wxBG0if+jzQe/qOr4iiI/7yHcD8irvHMPXvuoH3G0FWeOZV5nbPT0w1aM436YMSbf9SCTDb9PGYNYail40WhMwf83zWo7AybrYf+qnNwl43N1iZZmmTjy4/IHXRKAyVV/N/jpEhhXiExbVtm/srTBy9cb9AZgPfW2sEaC+jNE7eOImznGqbnK0ZoaWEy9iTxu2R7igUFQF+5+K4Ns7hAWBDsWk9PJKiD9UBy9F+OGUmIYdg8ktDl6iK1goIhMHntDEDxvrGBCTXQbnc3at4mhGm4YoIZ5Ov8jnSEmD+GGteNFRQcdcpepHBI1rd3erpGkvK3fDB4o5IkqkEsPVlXli5zx/5z8k4hOzs1Eo2WhWgbJ5Y7iDf8pne4NjgIcuVvjh0+slD6WziUP+Gg2bXPMRkPnfNbk317F0HRPntebLYVHruJnnlDxgHO9YdLUpRD899ovlH7S3yiHkWkIuwK4bhEBQEQ7tLn+bGnf6h0ypP/bYNMSl7JDRei7ScYUSac=
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
