dist: xenial
language: python
python:
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb gimp python python-pip
  - sudo pip2 install numpy typing
install:
  - pip install pytest setuptools
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest -c pytest.ini --maxfail=2 pgimp
