version: '2'

services:
  pgimp-ubuntu-16.04:
    build:
      context: .
      dockerfile: test/envs/linux/ubuntu/16.04/Dockerfile
    image: mabu/pgimp-ubuntu-16.04:latest
    volumes:
      - ./:/src
  pgimp-ubuntu-18.04:
    build:
      context: .
      dockerfile: test/envs/linux/ubuntu/18.04/Dockerfile
    image: mabu/pgimp-ubuntu-18.04:latest
    volumes:
      - ./:/src
  pgimp-centos-7.4:
    build:
      context: .
      dockerfile: test/envs/linux/centos/7.4/Dockerfile
    image: mabu/pgimp-centos-7.4:latest
    volumes:
      - ./:/src
  pgimp-centos-7.6:
    build:
      context: .
      dockerfile: test/envs/linux/centos/7.6/Dockerfile
    image: mabu/pgimp-centos-7.6:latest
    volumes:
      - ./:/src
