version: '2.1'

services:
  pgimp-ubuntu-16.04:
    build:
      context: .
      dockerfile: test/envs/linux/ubuntu/16.04/Dockerfile
    image: mabu/pgimp-ubuntu-16.04:latest
    volumes:
      - ./:/src
    shm_size: '256m'
  pgimp-ubuntu-18.04:
    build:
      context: .
      dockerfile: test/envs/linux/ubuntu/18.04/Dockerfile
    image: mabu/pgimp-ubuntu-18.04:latest
    volumes:
      - ./:/src
    shm_size: '256m'
  pgimp-ubuntu-20.04:
    build:
      context: .
      dockerfile: test/envs/linux/ubuntu/20.04/Dockerfile
    image: mabu/pgimp-ubuntu-20.04:latest
    volumes:
      - ./:/src
    shm_size: '256m'
  pgimp-ubuntu-20.04-installation:
    build:
      context: .
      dockerfile: test/installation/linux/ubuntu/20.04/Dockerfile
    image: mabu/pgimp-ubuntu-20.04:latest
    volumes:
      - ./:/src
  pgimp-centos-7.4:
    build:
      context: .
      dockerfile: test/envs/linux/centos/7.4/Dockerfile
    image: mabu/pgimp-centos-7.4:latest
    volumes:
      - ./:/src
    shm_size: '256m'
  pgimp-centos-7.6:
    build:
      context: .
      dockerfile: test/envs/linux/centos/7.6/Dockerfile
    image: mabu/pgimp-centos-7.6:latest
    volumes:
      - ./:/src
    shm_size: '256m'
